# Generated by Django 5.0.4 on 2024-05-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='article',
        ),
    ]
