# Generated by Django 5.0.4 on 2024-05-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_answer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passwordquestion'),
        ),
    ]
